8391256: TestZoneTextPrinterParser.java assertion fails with expected: <Mountain Standard Time> but was: <Mountain Daylight Time>
Reviewed-by: sgehwolf, andrew
Backport-of: 679d0b6ad621a002329474e7eeaefe8bada1ad34
(cherry picked from commit 5751c35809bf60a00e983251b4d570222aeca163)